[build]
  publish = "/"

# Corrected redirect rules
[[redirects]]
  from = "/aiAbout"
  to = "/"
  status = 301
force = true
[[redirects]]
  from = "/aiAbout/*"
  to = "/:splat"
  status = 301
  force = true
